#!/bin/bash
LJ_VER="core-2.1"
LJ_EXEC="$(pwd)"
LJ_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ "$(uname)" == "Darwin" ]; then
  LJ_SYS="osx"
  LJ_ARCH="$LJ_ROOT""/""$LJ_SYS"
  LJ_CORE="$LJ_ROOT""/""$LJ_VER""/""$LJ_SYS"
  LJ_LUA_PATH="$LJ_ROOT""/?.lua;""$LJ_ROOT""/?/init.lua;""$LJ_ARCH""/?.lua;""$LJ_ARCH""/?/init.lua;""$LJ_CORE""/?.lua;""$LJ_CORE""/?/init.lua;"
  LJ_LUA_CPATH="$LJ_ARCH""/?.so;""$LJ_ARCH""/loadall.so;""$LJ_CORE""/?.so;""$LJ_CORE""/loadall.so;"
  LUA_EXEC="$LJ_EXEC" LUA_ROOT="$LJ_ROOT" LUA_PATH="$LJ_LUA_PATH" LUA_CPATH="$LJ_LUA_CPATH" DYLD_LIBRARY_PATH="$LJ_CORE" "$LJ_CORE""/"luajit $@
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  LJ_SYS="linux"
  LJ_ARCH="$LJ_ROOT""/""$LJ_SYS"
  LJ_CORE="$LJ_ROOT""/""$LJ_VER""/""$LJ_SYS"
  LJ_LUA_PATH="$LJ_ROOT""/?.lua;""$LJ_ROOT""/?/init.lua;""$LJ_ARCH""/?.lua;""$LJ_ARCH""/?/init.lua;""$LJ_CORE""/?.lua;""$LJ_CORE""/?/init.lua;"
  LJ_LUA_CPATH="$LJ_ARCH""/?.so;""$LJ_ARCH""/loadall.so;""$LJ_CORE""/?.so;""$LJ_CORE""/loadall.so;"
  LUA_EXEC="$LJ_EXEC" LUA_ROOT="$LJ_ROOT" LUA_PATH="$LJ_LUA_PATH" LUA_CPATH="$LJ_LUA_CPATH" LD_LIBRARY_PATH="$LJ_CORE" LD_PRELOAD="libpthread.so.0" "$LJ_CORE""/"luajit $@
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
  "$LJ_CORE""/"luajit.cmd $@
elif [ "$(expr substr $(uname -s) 1 9)" == "CYGWIN_NT" ]; then
  "$LJ_CORE""/"luajit.cmd $@
else
  echo "ERROR - Unsupported system: "$(uname -s) 1>&2
  exit 1
fi
